#!/usr/bin/env python3
"""Put everything the app needs to run the CLI inside the app.

The desktop app holds no logic of its own: every question it answers goes
through the PassBook CLI. That is a good design and it had one bad consequence
— the app was shipped without the thing it depends on. On Windows, where there
is no system Python at all, a fresh install opened to
"Could not run PassBook: program not found" and the README's only setup route
was `install.sh`, which is a shell script Windows cannot run.

So the app carries the CLI now:

    cli/        the PassBook Python modules
    runtime/    a private Python that can run them          (Windows only)
    bin/        `passbook` and its 43 aliases, as .cmd shims (Windows only)

macOS and Linux always have a Python 3 to hand, so they get `cli/` and find an
interpreter at runtime. Windows gets the interpreter too, because assuming one
there is how this bug happened in the first place.

    python3 scripts/stage-runtime.py            # cli/ and bin/
    python3 scripts/stage-runtime.py --runtime  # ... and the Windows Python

`--runtime` downloads the official embeddable distribution from python.org and
refuses to use it unless it hashes to the value pinned below. Nothing here is
committed; the release build stages it and the bundler picks it up.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# The modules live under src/, which is where setuptools looks too.
SRC = ROOT / "src"
TAURI = ROOT / "app/src-tauri"
CLI_DIR = TAURI / "cli"
BIN_DIR = TAURI / "bin"
RUNTIME_DIR = TAURI / "runtime"

# Pinned so a release cannot be handed a different interpreter than the one
# this was tested against. The hash is of the file python.org served over TLS;
# recording it stops a later build silently getting something else.
PYTHON_VERSION = "3.12.7"
PYTHON_URL = (
    f"https://www.python.org/ftp/python/{PYTHON_VERSION}/"
    f"python-{PYTHON_VERSION}-embed-amd64.zip"
)
PYTHON_SHA256 = "0d57bb6cb078b74d23dbfe91f77d6780d45bed328911609f1f7ee2ba1606bf44"

# The embeddable distribution ships a `._pth` file that replaces sys.path
# outright — including the usual "directory of the script" entry. Without a
# line for the modules, `python.exe cli/passbook_cli.py` starts and then cannot
# import `passbook`.
PTH_NAME = "python312._pth"

# Kept strictly ASCII: a .cmd is read in whatever codepage the console happens
# to be in, and a stray byte in a comment can end the batch file early.
SHIM = """@echo off
REM PassBook - generated by scripts/stage-runtime.py. Safe to delete.
REM %%~dp0 is this file's own folder, so the install can be moved or renamed.
REM setlocal keeps PASSBOOK_INVOKED_AS out of the prompt that ran this, and
REM exit /b hands back the command's own status rather than the shim's.
setlocal
set "PASSBOOK_INVOKED_AS=%(name)s"
REM Bytecode goes somewhere writable and disposable. Left to itself Python
REM writes __pycache__ beside the modules, which is inside the installed app:
REM the uninstaller only removes what it installed, so those .pyc files kept
REM the install directory alive after an uninstall, and under a per-machine
REM install the directory is not writable at all.
set "PYTHONPYCACHEPREFIX=%%TEMP%%\\passbook-pycache"
"%%~dp0..\\runtime\\python.exe" "%%~dp0..\\cli\\passbook_cli.py" %%*
exit /b %%ERRORLEVEL%%
"""


def say(message: str) -> None:
    print(message, flush=True)


def stage_cli() -> list[str]:
    """Copy the Python modules the CLI is made of."""
    if CLI_DIR.exists():
        shutil.rmtree(CLI_DIR)
    CLI_DIR.mkdir(parents=True)
    copied = []
    for source in sorted(SRC.glob("passbook*.py")):
        shutil.copy2(source, CLI_DIR / source.name)
        copied.append(source.name)
    # Shipped alongside the code they cover, because this directory is
    # redistributed inside every installer.
    for extra in ("LICENSE", "NOTICE"):
        if (ROOT / extra).exists():
            shutil.copy2(ROOT / extra, CLI_DIR / extra)
    say(f"cli:      {len(copied)} modules -> {CLI_DIR.relative_to(ROOT)}")
    return copied


def alias_names() -> list[str]:
    """Every command name, asked of the CLI rather than written down here."""
    done = subprocess.run(
        [sys.executable, "-c",
         "import passbook_cli, json; print(json.dumps(sorted(passbook_cli.aliases())))"],
        cwd=str(SRC), capture_output=True, text=True, check=True,
    )
    return ["passbook", *json.loads(done.stdout)]


def stage_shims() -> list[str]:
    """A .cmd per command, so `passbook` works in a Windows terminal.

    Windows resolves a bare `passbook` to `passbook.cmd` through PATHEXT. The
    shims address the runtime relatively, so nothing has to be rewritten if the
    install directory moves.
    """
    if BIN_DIR.exists():
        shutil.rmtree(BIN_DIR)
    BIN_DIR.mkdir(parents=True)
    names = alias_names()
    for name in names:
        # CRLF, written as bytes so no platform translates them again. A .cmd
        # with Unix endings runs, but `set "X=y"` takes the stray CR into the
        # value, and the alias then matches nothing.
        body = (SHIM % {"name": name}).replace("\n", "\r\n")
        (BIN_DIR / f"{name}.cmd").write_bytes(body.encode("ascii"))
    say(f"shims:    {len(names)} commands -> {BIN_DIR.relative_to(ROOT)}")
    return names


def fetch_python(cache: Path) -> Path:
    cache.mkdir(parents=True, exist_ok=True)
    archive = cache / f"python-{PYTHON_VERSION}-embed-amd64.zip"
    if not archive.exists():
        say(f"runtime:  downloading {PYTHON_URL}")
        with urllib.request.urlopen(PYTHON_URL, timeout=120) as response:
            archive.write_bytes(response.read())
    got = hashlib.sha256(archive.read_bytes()).hexdigest()
    if got != PYTHON_SHA256:
        archive.unlink(missing_ok=True)
        raise SystemExit(
            f"the Python download does not match its pin\n"
            f"  expected {PYTHON_SHA256}\n  got      {got}")
    say(f"runtime:  python {PYTHON_VERSION}, hash verified")
    return archive


def stage_runtime(cache: Path) -> None:
    """Unpack a private Python and put `cryptography` in it.

    Sealing and linking need `cryptography`, and an app that ships without it
    would present encryption as an optional extra that is switched off for
    everybody who did not go and install something first.
    """
    archive = fetch_python(cache)
    if RUNTIME_DIR.exists():
        shutil.rmtree(RUNTIME_DIR)
    RUNTIME_DIR.mkdir(parents=True)
    with zipfile.ZipFile(archive) as bundle:
        bundle.extractall(RUNTIME_DIR)

    pth = RUNTIME_DIR / PTH_NAME
    if not pth.exists():
        raise SystemExit(f"no {PTH_NAME} in the distribution; the layout changed")
    lines = pth.read_text(encoding="utf-8").splitlines()
    if "..\\cli" not in lines:
        lines.append("..\\cli")
    pth.write_text("\n".join(lines) + "\n", encoding="utf-8")
    say(f"runtime:  {PTH_NAME} points at ..\\cli")

    # `--target .` next to python.exe, which the stock `._pth` already has on
    # sys.path. The embeddable distribution has no pip of its own, so this runs
    # under whichever Python is doing the build.
    #
    # The platform is named rather than inherited. Left to itself pip resolves a
    # wheel for the machine doing the building, so staging this on a Mac put a
    # macOS `cryptography` inside a Windows runtime and said nothing — the kind
    # of thing that only surfaces on a user's desktop.
    done = subprocess.run(
        [sys.executable, "-m", "pip", "install", "--quiet", "--disable-pip-version-check",
         "--only-binary=:all:", "--platform", "win_amd64",
         "--python-version", "3.12", "--implementation", "cp",
         "--target", str(RUNTIME_DIR), "cryptography>=41"],
        capture_output=True, text=True,
    )
    if done.returncode != 0:
        raise SystemExit(f"could not add cryptography:\n{done.stderr.strip()}")
    # Asked of the files rather than of pip's exit code: the compiled extension
    # is the part that has to be the Windows one, and it is the part a
    # host-resolved wheel gets wrong.
    binaries = sorted(p.name for p in RUNTIME_DIR.rglob("_rust.*"))
    if not any(name.endswith(".pyd") for name in binaries):
        raise SystemExit(
            "cryptography did not bring a Windows extension module; "
            f"found {binaries or 'nothing'}")
    installed = sorted(p.name for p in RUNTIME_DIR.glob("cryptography-*.dist-info"))
    say(f"runtime:  {installed[0] if installed else 'cryptography'} ({', '.join(binaries)})")
    say(f"runtime:  -> {RUNTIME_DIR.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", action="store_true",
                        help="also stage the private Windows Python (needs network)")
    parser.add_argument("--cache", default=str(TAURI / ".runtime-cache"),
                        help="where to keep the downloaded archive")
    parser.add_argument("--clean", action="store_true", help="remove everything staged")
    args = parser.parse_args()

    if args.clean:
        for directory in (CLI_DIR, BIN_DIR, RUNTIME_DIR):
            if directory.exists():
                shutil.rmtree(directory)
                say(f"removed {directory.relative_to(ROOT)}")
        return 0

    stage_cli()
    stage_shims()
    if args.runtime:
        stage_runtime(Path(args.cache))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
