#!/usr/bin/env python3
"""Keep the window's ACL in step with the commands it actually has.

The window is served over http://localhost so that WebAuthn has a domain to
bind a passkey to. That makes it a *remote* origin as far as Tauri is
concerned, and Tauri will not expose a command to a remote origin unless a
capability names it. Miss one and the window loads, looks right, and answers
"Command <name> not allowed by ACL" the moment somebody uses that feature.

So the list is generated from `generate_handler!` rather than typed, and
`tests/test_passbook_app_contract.py` fails if the two drift apart.

    python3 scripts/sync-permissions.py
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MAIN = ROOT / "app/src-tauri/src/main.rs"
CAPABILITY = ROOT / "app/src-tauri/capabilities/default.json"
PERMISSIONS = ROOT / "app/src-tauri/permissions/autogenerated"
BASE = ["core:default", "notification:default"]


def commands() -> list[str]:
    source = MAIN.read_text(encoding="utf-8")
    block = re.search(r"tauri::generate_handler!\[(.*?)\]", source, re.S)
    if not block:
        raise SystemExit("no generate_handler! block in main.rs")
    seen = dict.fromkeys(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", block.group(1)))
    return [name for name in seen if f"fn {name}(" in source]


def write(check: bool = False) -> int:
    names = commands()
    stale = 0

    PERMISSIONS.mkdir(parents=True, exist_ok=True)
    wanted = {f"{name}.toml" for name in names}
    for name in names:
        kebab = name.replace("_", "-")
        body = (
            "# Automatically generated by scripts/sync-permissions.py - DO NOT EDIT!\n\n"
            "[[permission]]\n"
            f'identifier = "allow-{kebab}"\n'
            f'description = "Enables the {name} command without any pre-configured scope."\n'
            f'commands.allow = ["{name}"]\n\n'
            "[[permission]]\n"
            f'identifier = "deny-{kebab}"\n'
            f'description = "Denies the {name} command without any pre-configured scope."\n'
            f'commands.deny = ["{name}"]\n'
        )
        path = PERMISSIONS / f"{name}.toml"
        if not path.exists() or path.read_text(encoding="utf-8") != body:
            stale += 1
            if not check:
                path.write_text(body, encoding="utf-8")
    for orphan in PERMISSIONS.glob("*.toml"):
        if orphan.name not in wanted:
            stale += 1
            if not check:
                orphan.unlink()

    capability = json.loads(CAPABILITY.read_text(encoding="utf-8"))
    granted = BASE + [f"allow-{name.replace('_', '-')}" for name in names]
    if capability.get("permissions") != granted:
        stale += 1
        if not check:
            capability["permissions"] = granted
            CAPABILITY.write_text(json.dumps(capability, indent=2) + "\n", encoding="utf-8")
    return stale


if __name__ == "__main__":
    checking = "--check" in sys.argv
    out_of_date = write(check=checking)
    if checking and out_of_date:
        print(f"{out_of_date} permission file(s) out of date — run scripts/sync-permissions.py")
        raise SystemExit(1)
    print("permissions in step" if not out_of_date else f"updated {out_of_date}")
